### PR TITLE
Updated work

### PR DESCRIPTION
**Pull request by jpoo90**
Addressed comments on old PR 
Updated pipeline to match latest changes

Having an issue with `sinon` when running the tests, more eyes here can help. :nerd_face:

### CODE REVIEW

**Comment by benmcosker** [comment]
looking at an issue with sinon dependency:
https://github.com/wallabyjs/public/issues/821

**Comment by obuckley-kenzan** [comment]
@jpoo90 
This invalidates #4 yes?  Should I close that one?

**Comment by benmcosker** [comment]
have implemented suggestions seen here:
https://github.com/xdissent/karma-chai/issues/5, but now getting:
```
  TypeError: undefined is not an object (evaluating 'window.chai.should')
  at node_modules/karma-chai-sinon/adapter.js:3

```

**Comment by paul-barry-kenzan** [comment]
@thescientist13 
Thinking this could closed as well.

**Pull request closed without merging**
